grails:
  profile: web
  codegen:
    defaultPackage: backend
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json: ['application/json', 'text/json']

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.cj.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL8Dialect
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:root}
  url: jdbc:mysql://localhost:3306/rick_morty_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
hibernate:
  hbm2ddl:
    auto: update
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

environments:
  development:
    dataSource:
      dbCreate: update
      driverClassName: com.mysql.cj.jdbc.Driver
      dialect: org.hibernate.dialect.MySQL8Dialect
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:root}
      url: jdbc:mysql://localhost:3306/rick_morty_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  test:
    dataSource:
      dbCreate: update
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
  debugh2:
    dataSource:
      dbCreate: update
      driverClassName: org.h2.Driver
      dialect: org.hibernate.dialect.H2Dialect
      username: sa
      password: ''
      url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  mysql:
    dataSource:
      dbCreate: update
      driverClassName: com.mysql.cj.jdbc.Driver
      dialect: org.hibernate.dialect.MySQL8Dialect
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:root}
      url: jdbc:mysql://localhost:3306/rick_morty_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  production:
    dataSource:
      dbCreate: update
      driverClassName: com.mysql.cj.jdbc.Driver
      dialect: org.hibernate.dialect.MySQL8Dialect
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:root}
      url: jdbc:mysql://localhost:3306/rick_morty_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

server:
  port: 8080
